# Generated by Django 2.2.10 on 2020-02-22 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'One of a kind'), (2, 'Limited supply'), (3, 'Unlimited supply')], default=1, verbose_name='type')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='base price')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('title_ru', models.CharField(max_length=120, verbose_name='название')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('description_ru', models.TextField(blank=True, default='', verbose_name='описание')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('image', models.ImageField(upload_to='product_images', verbose_name='image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.Product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
    ]
