# Generated by Django 2.2.10 on 2020-03-04 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200222_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('created_at',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='title_en',
        ),
    ]
