# Generated by Django 2.2.12 on 2020-04-24 23:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200304_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=8, verbose_name='weight (g)'),
        ),
    ]
