# Generated by Django 2.2.12 on 2020-04-26 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='supply_type',
        ),
    ]
