# Generated by Django 2.2.12 on 2020-04-26 00:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200425_0014'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmed at')),
                ('is_virtual', models.BooleanField(default=False, verbose_name='virtual delivery')),
                ('address_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='snapshot of address')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='additional data for shop administrator')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='users.Address', verbose_name='address')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='orders.Order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'delivery',
                'verbose_name_plural': 'deliveries',
            },
        ),
        migrations.AddField(
            model_name='orderline',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='orders.Delivery', verbose_name='delivery record'),
        ),
    ]
